### ISSUE TITLE
Referencing Module's Model

### ISSUE THREAD

**Issue by omdesignz** [sebastiaanluca/laravel-module-loader#2]
Hi there Sebastian,

I'm trying out this package but I can't seem to figure out how to reference a module's model within a given controller.

Regards

**Comment by sebastiaanluca** [comment]
Thanks for trying it out! :)

It's not really specific to this package, but more related to PHP namespaces. Think of it like using a class that belongs to a package you installed. Your model should have a namespace, like you would create a model in your app namespace (`namespace App\Models\User` for example):

```php
<?php

namespace YourModule\Models\User;

class User {}
```

Then you can just use your model in your controller by importing it:

```php
<?php

namespace App\Controllers\UserController;

use YourModule\Models\User;

class UserController extends Controller
{
    public function index(User $users)
    {
        $users = $users->all();
    }
}
```

Hope that clears things up. Let me know if this doesn't work. Feel free to post your model and controller code so I can help you better.

**Comment by omdesignz** [comment]
Thanks for the prompt reply. I guess I must be doing something wrong.

Model:
```php
<?php

namespace User\Models\User;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
```

Controller:
```php
<?php

namespace App\Http\Controllers;
use User\Models\User;

use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $users)
    {
        return $users->all();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        // dd($users);
        // $users = ['John', 'Henry'];
        return view('user::create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
```

The Model is found in the "modules\User\Models" folder.
The Controller is Found in the "App\Http\Controllers".

I actually get the "Class User\Models\User does not exist" error. Although the code editor is able to automatically navigate to the specified class.

Thanks

**Comment by sebastiaanluca** [comment]
Edited your reply to add some code tags ;)

I think you're missing a `src/` folder in your module. See https://github.com/sebastiaanluca/laravel-module-loader#creating-a-module for more information on how to automatically or manually create or structure a module.

If your `composer.json` file reads something like `"User\\": "modules/User/src/"`, then your classes should be in the `src/` directory. Of course you can manually override that by removing the `src/` directory so you don't have to use it, but it's advised to keep it so you have your config, resources, etc directories alongside your module classes' source directory.

Can you post your `composer.json` file, or at least the autoload blocks?

**Comment by omdesignz** [comment]
Thank you so much for the patience Sebastian.

Running:
`php artisan modules:refresh`

Seems to have been the fix. Now I kinda feel dumb!

I will continue to keep testing it because I wanna organize my code for an app I'm developing and I was immediately drawn to it because of its small but effective footprint.

Just a quick Q: do controllers work in a similar way? ie: add an Http\Controllers folder and everything works.

**Comment by sebastiaanluca** [comment]
What `modules:refresh` does is scan your modules directory for modules, add those to your composer.json, and refresh the Composer cache so any new modules (and classes) are detected and can be used. Just gotta make sure the module directory structure is correct so it detects your module.

I've been using modules for the past few years and I can't imagine dumping all my classes and files in `app/` anymore 😊

You can add as many directories and classes under the `src/` directory in your module as you like. No need to refresh modules or run `composer dumpautoload`. Since you already loaded the namespace, all new classes can be used right away by importing them in your class, just like you would for a class in the `App` namespace (but instead of `App\Models\User`, it'd be something like `User\Models\User` :)). Only time you need to refresh modules is when you add or remove one, or add non-namespaced classes to your factories, seeds, etc directories.

Good luck!
