### ISSUE TITLE
Support for Laravel 7

### ISSUE THREAD

**Issue by shaista-naushin** [sebastiaanluca/laravel-module-loader#8]
Readme says laravel 7 or higher is required for this package but i am unable to install on laravel 7.18.0. Will you be providing support for laravel 7 ?

Thanks

**Comment by shellprog** [comment]
Looking forward for Laravel 7 support

**Comment by sebastiaanluca** [comment]
Sorry, missed this issue! Upgraded the requirements to PHP 8and Laravel 8. Let me know if you have any issues.
